import { Routes } from '@angular/router';

import { DashboardComponent } from '../../pages/dashboard/dashboard.component';
//import { IconsComponent } from '../../pages/icons/icons.component';
import { MapsComponent } from '../../pages/maps/maps.component';
import { UserProfileComponent } from '../../pages/user-profile/user-profile.component';
//import { TablesComponent } from '../../pages/tables/tables.component';
import { MySuiteComponent } from '../../pages/my-suite/my-suite.component';
import { AssistedPurchaseComponent } from '../../pages/assisted-purchase/assisted-purchase.component';
import { ShippingCalculatorComponent } from '../../pages/shipping-calculator/shipping-calculator.component';
import { ProhibitedItemsComponent } from '../../pages/prohibited-items/prohibited-items.component';
import { CategoryComponent } from '../../pages/category/category.component';
import { EditprofileComponent } from '../../pages/editprofile/editprofile.component';
import { ItemComponent } from '../../pages/item/item.component';
import { UserComponent } from '../../pages/user/user.component';
import { SubcategoryComponent } from '../../pages/subcategory/subcategory.component';
import { ShipmentuserComponent } from '../../pages/shipmentuser/shipmentuser.component';
import { PickupuserComponent } from '../../pages/pickupuser/pickupuser.component';
export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'user-profile', component: UserProfileComponent },
    { path: 'subcategory', component: SubcategoryComponent },
    { path: 'user', component: UserComponent },
    { path: 'pickuplist', component: PickupuserComponent },
    { path: 'pickup', component: MapsComponent },
    { path: 'mysuite', component: MySuiteComponent },
    { path: 'shipmentuser', component: ShipmentuserComponent },
    { path: 'purchase', component: AssistedPurchaseComponent },
    { path: 'ShippingCalculator', component: ShippingCalculatorComponent },
    { path: 'ProhibitedItems', component: ProhibitedItemsComponent },
    { path: 'category', component: CategoryComponent },
    { path: 'editprofile', component: EditprofileComponent },
    { path: 'item', component: ItemComponent }
];
